### PR TITLE
feat(master-layout): add removable links feature to navigation component

### PR DESCRIPTION
**Pull request by crabouif**
The update introduces a new functionality for links to be removed from the navigation menu.

### CODE REVIEW

**Comment by crabouif** [comment]
Hi Olivier,

Yes you're right the purpose is to be able to remove a link (tab). 

In our application, we use links as tabs to show worspaces of users and sometimes if would be cool to be able to close it. We already did it by clicking a button, but it's not so smart...

**Comment by OlivierPerceboisGarve** [comment]
We discussed your PR in the team. We globally like this feature, but as said it is too late to have it into Oblique 11. 
We will consider integrating it into an upcoming release, even tough we can not give any guarantee, for now.
There also a bit of testing necessary, and there is a few edges cases to address, for instance what happens when the last item of a menu is being removed.

**Comment by nina-egger** [comment]
Note: 
- This is from the issue https://github.com/oblique-bit/oblique/issues/109 
- The progress of the feature request tracked in OUI-2656.

**Comment by nina-egger** [comment]
@gillerr since we will do that from our side should I close this PR?

**Comment by gillerr** [comment]
@crabouif This took a long time, but we finally got it. This will be available with Oblique 13.2.0

**Pull request closed without merging**
